### ISSUE TITLE
Repeated calls of MRPreclassification.trainingCompleted for a single excercise set

### ISSUE THREAD

**Issue by tmbo** [muvr/muvr-ios#15]
From time to time the `trainingCompleted ` completed hook on the `MRPreclassification` class gets called more than once for a single exercise. Most commonly that happens with longer exercise sessions (e.g. 45 seconds).

This results in training examples getting logged more than once.

**Comment by janm399** [comment]
I think I might know why that's happening: sometimes the PebbleKit repeats the last BT message. I think this may have something to do with _acks_ on the BT connection, which get lost, so the Pebble repeats the last message.

We'll need to work out a mechanism for detecting up to _n_ duplicates. This means that instead of using ``am_send_simple(const /*: uint32_t */, 0)`` in the watch code, we'll have to modify the constant in a way that allows us to detect duplicate.

The constant is a kind of "instruction kind" that matches the constants in ``MRRawPebbleConnectedDevice.MRPebbleDeviceSession`` in the iOS codebase. We have very few instructions compared to the ``uint32_t`` range, but I think it will be sufficient to detect some small _n_ duplicate transmissions, say 5.

**Comment by tmbo** [comment]
Thats great. Based on that I will create some exercise - noexercise session and we can have a look at how that goes.

**Comment by janm399** [comment]
This should do the trick; "it works on my hardware" :) I'll check the Scala server to see if it does the right thing tomorrow.

**Comment by tmbo** [comment]
I also sped up the classification which should result in fever resends anyhow. Will have a look at classification results tomorrow.

**Comment by janm399** [comment]
I'll also work on https://github.com/muvr/muvr-pebble/issues/4
