### ISSUE TITLE
sensor_fata_fuser cleanup

### ISSUE THREAD

**Issue by janm399** [muvr/muvr-ios#22]
Consider removing the exercise / no exercise decider from the sensor_data_fuser.

**Comment by tmbo** [comment]
Do you have a different place in mind where we would do that?

I will try to get some results with the exercise-noexercise model. Unfortunately since yesterday every spark job I start on my cassandra instance needs 12 gb of memory and fills up all my HDD space till it crashes. So no results there yet.

Nevertheless, we might have two different options:
  - train a model that does a binary classification between exercise-noexercise and a seperate model for exercise classification
  - or train a single model that contains a class `0` with the meaning of noexercise and all exercise classes

**Comment by janm399** [comment]
It might make sense to do some coarse filtering into broad classes (initially maybe even exercise / no-exercise), and then apply finer filters to that. In any case, that code should not be in the sensor data fuser, that should only deal with sensor data decoding and alignment.

**Comment by janm399** [comment]
This is becoming obsolete with https://github.com/muvr/muvr-ios/tree/feature/sd.
